### ISSUE TITLE
Errores validando NIF

### ISSUE THREAD

**Issue by mpijierro** [skilla/ValidatorCifNifNie#4]
Hola,

en primer lugar enhorabuena por tu trabajo. En segundo lugar te escribo porque estoy teniendo errores en la validación de todos los NIF's. Estoy usando para probar varios generados de nifs online o incluso probando con el mío propio y siempre me retorna un false.

Por ejemplo, una llamada con este valor:  isValidNIF('14167864W')  me retorna false y es un nif correcto. O, incluso, como te comenté anteriormente, con el mío propio que no lo tengo por mantener la privacidad.

No puedo ponerte más código ya que básicamente es eso lo que falla. 

También he probado CIF y NIE y casi todos son válidos. Casi todos.

Eso es todo.

Gracias por tu tiempo.

**Comment by skilla** [comment]
Hola Manu,

Gracias por tu "pull request", ya está mergeada.

Por otro lado las validaciones son correctas, lo que pasa es que estás validando '14167864W' como NIF y esta opción es para personas jurídicas, tienes que hacerlo como DNI isValidDNI(''14167864W'), al hacer la recopilación de formatos intenté leer todo lo que pude en los BOEs y otra documentación oficial y la verdad es que todo estaba a trozos y como coincidía  con la info de Wikipedia https://es.wikipedia.org/wiki/N%C3%BAmero_de_identificaci%C3%B3n_fiscal use esa misma nomenclatura.

Un saludo
Sergio Zambrano

P.D. a ver si nos vemos en el deSymfony de castellón

**Comment by mpijierro** [comment]
Hola,

muy bien, entendido. Ya me extrañaba a mi...y ya sabía yo que estaba haciendo algo mal, pero no daba con la razón. En fin.

Muchas gracias nuevamente por todo.

Un saludo :)

**Comment by josevavia** [comment]
Hola!

Retomo esta conversación para informar, simplemente, de que desde hace ya un tiempo para las personas físicas también se usa el NIF, en realidad el concepto de "DNI" ha quedado relegado al documento en si (el carnet), pero el número es NIF sea para personas físicas, jurídicas o empresas. Dicho de otra manera, que cualquiera de nuestros DNI debería pasar la validación de NIF y por lo que veo no lo hace...

No se si está bien que utilice esta conversación o si debería abrir una nueva, si es así pido perdón de antemano.

Saludos,
